[runner]
required = [
  "black",
  "clang-format",
  "clippier_md",
  "nixfmt",
  "prettier",
  "shfmt",
  "stylua",
  "taplo",
]
skip = [
  "alejandra",
  "autopep8",
  "bandit",
  "biome",
  "codespell",
  "csharpier",
  "cspell",
  "deadnix",
  "deno",
  "dprint",
  "eslint",
  "flake8",
  "isort",
  "luacheck",
  "markdownlint",
  "mdformat",
  "mypy",
  "oxfmt",
  "oxlint",
  "pylint",
  "pyright",
  "remark",
  "ruff",
  "rumdl",
  "selene",
  "shellcheck",
  "statix",
  "stylelint",
  "ty",
  "vale",
  "yamlfmt",
  "yamllint",
  "yapf",
]

[runner.tools]
black = { mode = "enabled", capabilities = [
  "format",
], format-extensions = [
  "py",
] }
clang-format = { mode = "enabled", capabilities = [
  "format",
], format-extensions = [
  "m",
] }
clippier_md = { mode = "enabled", capabilities = [
  "format",
], format-extensions = [
  "md",
] }
nixfmt = { mode = "enabled", capabilities = [
  "format",
], format-extensions = [
  "nix",
] }
prettier = { mode = "enabled", capabilities = [
  "format",
], format-extensions = [
  "css",
  "json",
  "ts",
  "yml",
] }
shfmt = { mode = "enabled", capabilities = [
  "format",
], format-extensions = [
  "sh",
] }
stylua = { mode = "enabled", capabilities = [
  "format",
], format-extensions = [
  "lua",
] }
taplo = { mode = "enabled", capabilities = [
  "format",
], format-extensions = [
  "toml",
] }
alejandra = { mode = "disabled" }
autopep8 = { mode = "disabled" }
bandit = { mode = "disabled" }
biome = { mode = "disabled" }
codespell = { mode = "disabled" }
csharpier = { mode = "disabled" }
cspell = { mode = "disabled" }
deadnix = { mode = "disabled" }
deno = { mode = "disabled" }
dprint = { mode = "disabled" }
eslint = { mode = "disabled" }
flake8 = { mode = "disabled" }
isort = { mode = "disabled" }
luacheck = { mode = "disabled" }
markdownlint = { mode = "disabled" }
mdformat = { mode = "disabled" }
mypy = { mode = "disabled" }
oxfmt = { mode = "disabled" }
oxlint = { mode = "disabled" }
pylint = { mode = "disabled" }
pyright = { mode = "disabled" }
remark = { mode = "disabled" }
ruff = { mode = "disabled" }
rumdl = { mode = "disabled" }
selene = { mode = "disabled" }
shellcheck = { mode = "disabled" }
statix = { mode = "disabled" }
stylelint = { mode = "disabled" }
ty = { mode = "disabled" }
vale = { mode = "disabled" }
yamlfmt = { mode = "disabled" }
yamllint = { mode = "disabled" }
yapf = { mode = "disabled" }
